[package]
name = "sometest"
version = "0.1.0"
edition = "2021"

repository = "https://github.com/duckinator/fakerepo"

[dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
