[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.26.0-github-omnibor"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
# Whether to embed dependency information using cargo-auditable
cargo-auditable = true
# Whether to use cargo-cyclonedx to generate an SBOM
cargo-cyclonedx = true
# Whether to use omnibor-cli to generate OmniBOR Artifact IDs
omnibor = true

[dist.minimum-glibc-version]
"*" = "2.17"
x86_64-unknown-linux-gnu = "2.18"
